language: node_js
node_js:
  - "node"
# https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
